package frc.robot.util;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.filter.LinearFilter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.wpilibj.Filesystem;
import frc.robot.RobotState;
import java.io.BufferedReader;
import java.nio.file.Files;
import java.nio.file.Path;
import lombok.Getter;
import lombok.Setter;
import org.littletonrobotics.junction.Logger;

/**
 * Calculates shooting parameters using interpolating lookup tables generated by
 * scripts/generate_lookup_table.py.
 */
public class ShotCalculator {
  private static final double LOOP_PERIOD_SECS = 0.02; // 20ms
  private static final double EPSILON = 1e-9;

  private static final double HUB_LOOKUP_SELECTION_X_THRESHOLD_METERS = 4.6;
  private static final double LOB_LOOKUP_SELECTION_Y_THRESHOLD_METERS = 4.0;
  private static final double LOB_PITCH_SCALE = 0.8;
  private static final double LOB_EXIT_VELOCITY_SCALE = 0.8;

  private static final LoggedTunableNumber accelerationFilterTimeConstantSecs =
      new LoggedTunableNumber("ShotCalculator/AccelerationFilterTimeConstantSecs", 0.12);
  private static final LoggedTunableNumber accelerationCompensationGain =
      new LoggedTunableNumber("ShotCalculator/AccelerationCompensationGain", 0.5);
  private static final LoggedTunableNumber maxAccelerationCompensationMps2 =
      new LoggedTunableNumber("ShotCalculator/MaxAccelerationCompensationMps2", 3.0);
  private static final LoggedTunableNumber releasePredictionSecs =
      new LoggedTunableNumber("ShotCalculator/ReleasePredictionSecs", 0.06);

  private static final LoggedTunableNumber stabilityGateEnabled =
      new LoggedTunableNumber("ShotCalculator/StabilityGateEnabled", 1.0);
  private static final LoggedTunableNumber stabilityMaxRobotToShotRatio =
      new LoggedTunableNumber("ShotCalculator/StabilityMaxRobotToShotRatio", 0.65);
  private static final LoggedTunableNumber stabilityMaxLeadAngleDeg =
      new LoggedTunableNumber("ShotCalculator/StabilityMaxLeadAngleDeg", 75.0);
  private static final LoggedTunableNumber stabilityMaxCompensationDistanceMeters =
      new LoggedTunableNumber("ShotCalculator/StabilityMaxCompensationDistanceMeters", 2.0);
  private static final LoggedTunableNumber stabilityMinCommandedHorizontalSpeedMps =
      new LoggedTunableNumber("ShotCalculator/StabilityMinCommandedHorizontalSpeedMps", 1.0);
  private static final LoggedTunableNumber stabilityMaxCommandedSpeedMps =
      new LoggedTunableNumber("ShotCalculator/StabilityMaxCommandedSpeedMps", 18.0);
  private static final LoggedTunableNumber stabilityMaxPitchDeg =
      new LoggedTunableNumber("ShotCalculator/StabilityMaxPitchDeg", 72.5);

  private static ShotCalculator instance;

  private enum ShotMode {
    HUB,
    FERRY,
    LOB_LEFT,
    LOB_RIGHT
  }

  public enum TargetingMode {
    AUTO
  }

  private static class LookupProfile {
    private final String name;

    private final InterpolatingDoubleTreeMap flightTimeMap = new InterpolatingDoubleTreeMap();
    private final InterpolatingDoubleTreeMap velocityVectorXMap = new InterpolatingDoubleTreeMap();
    private final InterpolatingDoubleTreeMap velocityVectorYMap = new InterpolatingDoubleTreeMap();
    private final InterpolatingDoubleTreeMap velocityVectorZMap = new InterpolatingDoubleTreeMap();

    private double shooterHeight = 0.5;
    private double targetHeight = 1.75;
    private double minDistance = Double.MAX_VALUE;
    private double maxDistance = 0.0;
    private boolean loaded = false;

    private LookupProfile(String name) {
      this.name = name;
    }
  }

  /** Shooting parameters for a given shot. */
  public record ShootingParameters(
      Rotation2d turretAngle,
      double turretVelocity,
      double pitchAngle,
      double pitchVelocity,
      double exitVelocity) {}

  private record CompensationSolution(
      Translation2d compensatedPosition, double lookaheadDistance) {}

  private record ShotSelection(
      ShotMode shotMode, LookupProfile lookupProfile, Translation2d targetPosition) {}

  private final LookupProfile hubLookupProfile = new LookupProfile("hub_lookup_vector.json");

  @Getter private double shooterHeight = 0.5;
  @Getter private double targetHeight = 1.75;
  @Getter private double minDistance = Double.MAX_VALUE;
  @Getter private double maxDistance = 0.0;
  @Getter private boolean loaded = false;
  @Getter private boolean shootOnMoveEnabled = true;
  @Getter @Setter private TargetingMode targetingMode = TargetingMode.AUTO;

  @Getter private boolean shotStable = false;

  // Filters for velocity calculation
  private final LinearFilter turretAngleFilter =
      LinearFilter.movingAverage((int) (0.1 / LOOP_PERIOD_SECS));
  private final LinearFilter pitchAngleFilter =
      LinearFilter.movingAverage((int) (0.1 / LOOP_PERIOD_SECS));

  // State for velocity calculation
  private Rotation2d lastTurretAngle = null;
  private double lastPitchAngle = Double.NaN;
  private Translation3d lastShooterFieldVelocity = null;
  private Translation3d filteredShooterFieldAcceleration = new Translation3d();

  // Robot to turret offset (adjust for your robot)
  private final Translation2d robotToTurret = new Translation2d(0.0, 0.0);

  public static ShotCalculator getInstance() {
    if (instance == null) instance = new ShotCalculator();
    return instance;
  }

  private ShotCalculator() {
    load();
  }

  /** Enables or disables shoot-on-the-move velocity compensation. */
  public void setShootOnMoveEnabled(boolean enabled) {
    this.shootOnMoveEnabled = enabled;
  }

  /** Loads shot lookups from the deploy directory. */
  private void load() {
    Path deployPath = Filesystem.getDeployDirectory().toPath();
    loadVectorLookup(deployPath.resolve("hub_lookup_vector.json"), hubLookupProfile);
    loaded = hubLookupProfile.loaded;
  }

  private void loadVectorLookup(Path path, LookupProfile profile) {
    profile.flightTimeMap.clear();
    profile.velocityVectorXMap.clear();
    profile.velocityVectorYMap.clear();
    profile.velocityVectorZMap.clear();
    profile.minDistance = Double.MAX_VALUE;
    profile.maxDistance = 0.0;

    try (BufferedReader reader = Files.newBufferedReader(path)) {
      Gson gson = new Gson();
      JsonObject root = gson.fromJson(reader, JsonObject.class);
      JsonObject config = root.getAsJsonObject("config");
      profile.shooterHeight = config.get("shooter_height_m").getAsDouble();
      profile.targetHeight = config.get("target_height_m").getAsDouble();

      JsonArray entriesJson = root.getAsJsonArray("entries");
      int count = 0;

      for (int i = 0; i < entriesJson.size(); i++) {
        JsonObject entry = entriesJson.get(i).getAsJsonObject();
        double distance = entry.get("distance").getAsDouble();
        JsonObject vector = entry.getAsJsonObject("velocity_vector_mps");
        double flightTime = entry.get("flight_time").getAsDouble();

        profile.velocityVectorXMap.put(distance, vector.get("x").getAsDouble());
        profile.velocityVectorYMap.put(distance, vector.get("y").getAsDouble());
        profile.velocityVectorZMap.put(distance, vector.get("z").getAsDouble());
        profile.flightTimeMap.put(distance, flightTime);
        profile.minDistance = Math.min(profile.minDistance, distance);
        profile.maxDistance = Math.max(profile.maxDistance, distance);
        count++;
      }

      profile.loaded = count > 0;
      if (profile.loaded) {
        System.out.println(
            "ShotCalculator: Loaded "
                + profile.name
                + " with "
                + count
                + " entries ("
                + profile.minDistance
                + "m - "
                + profile.maxDistance
                + "m)");
      }
    } catch (Exception e) {
      profile.loaded = false;
      System.err.println("ShotCalculator: Failed to load " + profile.name + ": " + e.getMessage());
    }
  }

  /** Calculates shot parameters for the current robot state. */
  public ShootingParameters getParameters() {
    if (!loaded) {
      shotStable = false;
      return new ShootingParameters(Rotation2d.kZero, 0.0, 0.0, 0.0, 0.0);
    }

    Pose2d robotPose = RobotState.getInstance().getRobotPose();
    ChassisSpeeds robotVelocity = RobotState.getInstance().getRobotVelocity();

    ShotSelection selection = selectShotSelection(robotPose);
    LookupProfile lookupProfile = selection.lookupProfile();
    if (!lookupProfile.loaded) {
      shotStable = false;
      Logger.recordOutput("ShotCalculator/ShotMode", selection.shotMode().name());
      Logger.recordOutput("ShotCalculator/VectorLookupLoaded", false);
      return new ShootingParameters(Rotation2d.kZero, 0.0, 0.0, 0.0, 0.0);
    }

    shooterHeight = lookupProfile.shooterHeight;
    targetHeight = lookupProfile.targetHeight;
    minDistance = lookupProfile.minDistance;
    maxDistance = lookupProfile.maxDistance;

    Translation2d targetPosition = selection.targetPosition();
    Translation2d turretPosition =
        robotPose.getTranslation().plus(robotToTurret.rotateBy(robotPose.getRotation()));
    Translation3d shooterFieldVelocity =
        ShotVectorCompensator.calculateShooterFieldVelocity(
            robotVelocity, robotPose.getRotation(), robotToTurret);
    Translation3d shooterFieldAcceleration = estimateShooterFieldAcceleration(shooterFieldVelocity);

    double currentDistance = targetPosition.getDistance(turretPosition);
    CompensationSolution compensationSolution =
        new CompensationSolution(turretPosition, clampDistance(currentDistance, lookupProfile));

    Rotation2d lookupYaw =
        normalizeTo0To2Pi(
            targetPosition.minus(compensationSolution.compensatedPosition()).getAngle());
    Translation3d lookupVector =
        getLookupVector(compensationSolution.lookaheadDistance(), lookupProfile);
    Translation3d requiredFieldVelocity =
        ShotVectorCompensator.orientLookupVectorToField(lookupVector, lookupYaw);
    double tof = lookupProfile.flightTimeMap.get(compensationSolution.lookaheadDistance());
    double predictionTimeSecs = Math.max(0.0, releasePredictionSecs.get());
    double accelGain = Math.max(0.0, accelerationCompensationGain.get());
    Translation3d weightedAcceleration = shooterFieldAcceleration.times(accelGain);
    Translation3d predictedShooterFieldVelocity =
        shooterFieldVelocity.plus(weightedAcceleration.times(predictionTimeSecs));

    ShotVectorCompensator.CompensatedShot shot =
        shootOnMoveEnabled
            ? ShotVectorCompensator.compensateWithShooterFieldVelocity(
                requiredFieldVelocity, predictedShooterFieldVelocity)
            : ShotVectorCompensator.fromShooterRelativeVector(requiredFieldVelocity);

    ShootingParameters requestedShot =
        new ShootingParameters(
            normalizeTo0To2Pi(shot.yaw()), 0.0, shot.pitch(), 0.0, shot.exitVelocity());
    boolean ferryShot = isFerryShotMode(selection.shotMode());
    boolean lobShot = isLobShotMode(selection.shotMode());
    if (ferryShot || lobShot) {
      requestedShot = applyLobScaling(requestedShot);
    }

    Rotation2d turretAngle = requestedShot.turretAngle();
    double pitchAngle = requestedShot.pitchAngle();
    double exitVelocity = requestedShot.exitVelocity();

    if (lastTurretAngle == null) lastTurretAngle = turretAngle;
    if (Double.isNaN(lastPitchAngle)) lastPitchAngle = pitchAngle;

    double turretVelocity =
        turretAngleFilter.calculate(
            turretAngle.minus(lastTurretAngle).getRadians() / LOOP_PERIOD_SECS);
    double pitchVelocity =
        pitchAngleFilter.calculate((pitchAngle - lastPitchAngle) / LOOP_PERIOD_SECS);

    lastTurretAngle = turretAngle;
    lastPitchAngle = pitchAngle;

    shotStable =
        evaluateStabilityGate(
            lookupYaw, shot, turretPosition, compensationSolution.compensatedPosition());

    Logger.recordOutput("ShotCalculator/ShootOnMoveEnabled", shootOnMoveEnabled);
    Logger.recordOutput("ShotCalculator/TargetingMode", targetingMode.name());
    Logger.recordOutput("ShotCalculator/VectorLookupLoaded", true);
    Logger.recordOutput("ShotCalculator/HubLookupLoaded", hubLookupProfile.loaded);
    Logger.recordOutput("ShotCalculator/ShotMode", selection.shotMode().name());
    Logger.recordOutput("ShotCalculator/FerryScalingApplied", ferryShot);
    Logger.recordOutput("ShotCalculator/LobScalingApplied", lobShot);
    Logger.recordOutput("ShotCalculator/ShotStable", shotStable);
    Logger.recordOutput("ShotCalculator/SelectionRobotX", robotPose.getX());
    Logger.recordOutput("ShotCalculator/SelectionRobotY", robotPose.getY());
    Logger.recordOutput(
        "ShotCalculator/TargetPosition",
        new double[] {targetPosition.getX(), targetPosition.getY()});
    Logger.recordOutput(
        "ShotCalculator/CompensatedPosition",
        new Pose2d(compensationSolution.compensatedPosition(), turretAngle));
    Logger.recordOutput(
        "ShotCalculator/TurretToTargetDistance", compensationSolution.lookaheadDistance());
    Logger.recordOutput("ShotCalculator/TimeOfFlightSec", tof);
    Logger.recordOutput("ShotCalculator/ReleasePredictionSec", predictionTimeSecs);
    Logger.recordOutput("ShotCalculator/AccelerationCompensationGain", accelGain);
    Logger.recordOutput("ShotCalculator/PitchAngleDeg", Math.toDegrees(pitchAngle));
    Logger.recordOutput("ShotCalculator/ExitVelocity", exitVelocity);
    Logger.recordOutput(
        "ShotCalculator/RequiredFieldVelocity",
        new double[] {
          shot.requiredFieldVelocity().getX(),
          shot.requiredFieldVelocity().getY(),
          shot.requiredFieldVelocity().getZ()
        });
    Logger.recordOutput(
        "ShotCalculator/ShooterFieldVelocity",
        new double[] {
          predictedShooterFieldVelocity.getX(),
          predictedShooterFieldVelocity.getY(),
          predictedShooterFieldVelocity.getZ()
        });
    Logger.recordOutput(
        "ShotCalculator/ShooterFieldAcceleration",
        new double[] {
          shooterFieldAcceleration.getX(),
          shooterFieldAcceleration.getY(),
          shooterFieldAcceleration.getZ()
        });
    Logger.recordOutput(
        "ShotCalculator/CommandedShooterVelocity",
        new double[] {
          shot.shooterRelativeVelocity().getX(),
          shot.shooterRelativeVelocity().getY(),
          shot.shooterRelativeVelocity().getZ()
        });

    return new ShootingParameters(
        turretAngle, turretVelocity, pitchAngle, pitchVelocity, exitVelocity);
  }

  private ShotSelection selectShotSelection(Pose2d robotPose) {
    if (RobotState.getInstance().isFerryShotRequested()
        && FieldConstants.Ferry.isRobotInNeutralZone(robotPose.getX())) {
      return new ShotSelection(
          ShotMode.FERRY,
          hubLookupProfile,
          FieldConstants.Ferry.getCloserTarget(robotPose.getTranslation()));
    }

    boolean flipFieldCoordinates = AllianceFlipUtil.shouldFlip();
    Logger.recordOutput("ShotCalculator/Alliance", flipFieldCoordinates ? "Red" : "Blue");

    ShotMode shotMode = selectShotMode(robotPose, flipFieldCoordinates);
    return switch (shotMode) {
      case HUB -> new ShotSelection(
          ShotMode.HUB,
          hubLookupProfile,
          FieldConstants.Hub.topCenterPoint.get().toTranslation2d());
      case FERRY -> new ShotSelection(
          ShotMode.FERRY,
          hubLookupProfile,
          FieldConstants.Ferry.getCloserTarget(robotPose.getTranslation()));
      case LOB_LEFT -> new ShotSelection(
          ShotMode.LOB_LEFT, hubLookupProfile, selectAllianceLobTarget(true, flipFieldCoordinates));
      case LOB_RIGHT -> new ShotSelection(
          ShotMode.LOB_RIGHT,
          hubLookupProfile,
          selectAllianceLobTarget(false, flipFieldCoordinates));
    };
  }

  static Translation2d selectAllianceLobTarget(boolean leftTarget, boolean flipFieldCoordinates) {
    Translation3d lobTarget =
        leftTarget
            ? (flipFieldCoordinates
                ? FieldConstants.Lob.LOB_LEFT.getRed()
                : FieldConstants.Lob.LOB_LEFT.getBlue())
            : (flipFieldCoordinates
                ? FieldConstants.Lob.LOB_RIGHT.getRed()
                : FieldConstants.Lob.LOB_RIGHT.getBlue());
    return lobTarget.toTranslation2d();
  }

  static ShotMode selectShotMode(Pose2d robotPose, boolean flipFieldCoordinates) {
    Translation2d selectionPosition =
        normalizeRobotPositionForShotSelection(robotPose, flipFieldCoordinates);

    if (selectionPosition.getX() < HUB_LOOKUP_SELECTION_X_THRESHOLD_METERS) {
      return ShotMode.HUB;
    }

    if (selectionPosition.getY() > LOB_LOOKUP_SELECTION_Y_THRESHOLD_METERS) {
      return ShotMode.LOB_LEFT;
    }

    return ShotMode.LOB_RIGHT;
  }

  private static Translation2d normalizeRobotPositionForShotSelection(
      Pose2d robotPose, boolean flipFieldCoordinates) {
    if (!flipFieldCoordinates) {
      return robotPose.getTranslation();
    }

    return new Translation2d(
        FieldConstants.fieldLength - robotPose.getX(),
        FieldConstants.fieldWidth - robotPose.getY());
  }

  private boolean evaluateStabilityGate(
      Rotation2d lookupYaw,
      ShotVectorCompensator.CompensatedShot shot,
      Translation2d turretPosition,
      Translation2d compensatedPosition) {
    if (!shootOnMoveEnabled || stabilityGateEnabled.get() < 0.5) {
      return true;
    }

    double requiredHorizontalSpeed =
        Math.hypot(shot.requiredFieldVelocity().getX(), shot.requiredFieldVelocity().getY());
    double shooterFieldHorizontalSpeed =
        Math.hypot(shot.shooterFieldVelocity().getX(), shot.shooterFieldVelocity().getY());
    double commandedHorizontalSpeed =
        Math.hypot(shot.shooterRelativeVelocity().getX(), shot.shooterRelativeVelocity().getY());
    double robotToShotRatio =
        shooterFieldHorizontalSpeed / Math.max(requiredHorizontalSpeed, EPSILON);
    double leadAngleDeg =
        Math.toDegrees(Math.abs(normalizeToMinusPiToPi(shot.yaw().minus(lookupYaw).getRadians())));
    double compensationDistance = turretPosition.getDistance(compensatedPosition);
    double maxPitchRad = Math.toRadians(stabilityMaxPitchDeg.get());

    boolean stable =
        Double.isFinite(shot.exitVelocity())
            && Double.isFinite(shot.pitch())
            && robotToShotRatio <= stabilityMaxRobotToShotRatio.get()
            && leadAngleDeg <= stabilityMaxLeadAngleDeg.get()
            && compensationDistance <= stabilityMaxCompensationDistanceMeters.get()
            && commandedHorizontalSpeed >= stabilityMinCommandedHorizontalSpeedMps.get()
            && shot.exitVelocity() <= stabilityMaxCommandedSpeedMps.get()
            && Math.abs(shot.pitch()) <= maxPitchRad;

    Logger.recordOutput("ShotCalculator/Stability/RobotToShotRatio", robotToShotRatio);
    Logger.recordOutput("ShotCalculator/Stability/LeadAngleDeg", leadAngleDeg);
    Logger.recordOutput("ShotCalculator/Stability/CompensationDistanceM", compensationDistance);
    Logger.recordOutput(
        "ShotCalculator/Stability/CommandedHorizontalSpeedMps", commandedHorizontalSpeed);
    Logger.recordOutput("ShotCalculator/Stability/CommandedPitchDeg", Math.toDegrees(shot.pitch()));

    return stable;
  }

  private Translation3d estimateShooterFieldAcceleration(Translation3d shooterFieldVelocity) {
    double timeConstant = Math.max(LOOP_PERIOD_SECS, accelerationFilterTimeConstantSecs.get());
    double alpha = LOOP_PERIOD_SECS / (timeConstant + LOOP_PERIOD_SECS);

    if (lastShooterFieldVelocity == null) {
      lastShooterFieldVelocity = shooterFieldVelocity;
      filteredShooterFieldAcceleration = new Translation3d();
      return filteredShooterFieldAcceleration;
    }

    Translation3d rawAcceleration =
        shooterFieldVelocity.minus(lastShooterFieldVelocity).div(LOOP_PERIOD_SECS);
    double maxAccel = Math.max(0.0, maxAccelerationCompensationMps2.get());
    rawAcceleration =
        new Translation3d(
            MathUtil.clamp(rawAcceleration.getX(), -maxAccel, maxAccel),
            MathUtil.clamp(rawAcceleration.getY(), -maxAccel, maxAccel),
            MathUtil.clamp(rawAcceleration.getZ(), -maxAccel, maxAccel));
    filteredShooterFieldAcceleration =
        new Translation3d(
            filteredShooterFieldAcceleration.getX()
                + alpha * (rawAcceleration.getX() - filteredShooterFieldAcceleration.getX()),
            filteredShooterFieldAcceleration.getY()
                + alpha * (rawAcceleration.getY() - filteredShooterFieldAcceleration.getY()),
            filteredShooterFieldAcceleration.getZ()
                + alpha * (rawAcceleration.getZ() - filteredShooterFieldAcceleration.getZ()));
    lastShooterFieldVelocity = shooterFieldVelocity;
    return filteredShooterFieldAcceleration;
  }

  private double clampDistance(double distance, LookupProfile lookupProfile) {
    return Math.max(lookupProfile.minDistance, Math.min(lookupProfile.maxDistance, distance));
  }

  static ShootingParameters applyLobScaling(ShootingParameters parameters) {
    return new ShootingParameters(
        parameters.turretAngle(),
        parameters.turretVelocity(),
        parameters.pitchAngle() * LOB_PITCH_SCALE,
        parameters.pitchVelocity() * LOB_PITCH_SCALE,
        parameters.exitVelocity() * LOB_EXIT_VELOCITY_SCALE);
  }

  private Translation3d getLookupVector(double distance, LookupProfile lookupProfile) {
    return new Translation3d(
        lookupProfile.velocityVectorXMap.get(distance),
        lookupProfile.velocityVectorYMap.get(distance),
        lookupProfile.velocityVectorZMap.get(distance));
  }

  private static boolean isLobShotMode(ShotMode shotMode) {
    return shotMode == ShotMode.LOB_LEFT || shotMode == ShotMode.LOB_RIGHT;
  }

  private static boolean isFerryShotMode(ShotMode shotMode) {
    return shotMode == ShotMode.FERRY;
  }

  private static Rotation2d normalizeTo0To2Pi(Rotation2d angle) {
    double angleRad = angle.getRadians();
    while (angleRad < 0) angleRad += 2 * Math.PI;
    while (angleRad >= 2 * Math.PI) angleRad -= 2 * Math.PI;
    return Rotation2d.fromRadians(angleRad);
  }

  private static double normalizeToMinusPiToPi(double angleRad) {
    return Math.atan2(Math.sin(angleRad), Math.cos(angleRad));
  }
}
