package frc.robot.util;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import edu.wpi.first.math.filter.LinearFilter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.wpilibj.Filesystem;
import frc.robot.RobotState;
import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import lombok.Getter;
import org.littletonrobotics.junction.Logger;

/**
 * Calculates shooting parameters using interpolating lookup tables. Tables are loaded from
 * deploy/trajectory_lookup.json, generated by scripts/generate_trajectory_lookup.py.
 */
public class ShotCalculator {
  private static final double LOOP_PERIOD_SECS = 0.02; // 20ms
  private static final int MAX_TOF_ITERATIONS = 5;
  private static final double TOF_CONVERGENCE_THRESHOLD = 0.001; // meters

  private static ShotCalculator instance;

  public static ShotCalculator getInstance() {
    if (instance == null) instance = new ShotCalculator();
    return instance;
  }

  /** Shooting parameters for a given shot. */
  public record ShootingParameters(
      Rotation2d turretAngle,
      double turretVelocity,
      double pitchAngle,
      double pitchVelocity,
      double exitVelocity) {}

  // Lookup tables keyed by distance (meters)
  private final InterpolatingDoubleTreeMap pitchAngleMap = new InterpolatingDoubleTreeMap();
  private final InterpolatingDoubleTreeMap exitVelocityMap = new InterpolatingDoubleTreeMap();
  private final InterpolatingDoubleTreeMap flightTimeMap = new InterpolatingDoubleTreeMap();

  @Getter private double shooterHeight = 0.5;
  @Getter private double targetHeight = 1.75;
  @Getter private double minDistance = Double.MAX_VALUE;
  @Getter private double maxDistance = 0;
  @Getter private boolean loaded = false;

  // Filters for velocity calculation
  private final LinearFilter turretAngleFilter =
      LinearFilter.movingAverage((int) (0.1 / LOOP_PERIOD_SECS));
  private final LinearFilter pitchAngleFilter =
      LinearFilter.movingAverage((int) (0.1 / LOOP_PERIOD_SECS));

  // State for velocity calculation
  private Rotation2d lastTurretAngle = null;
  private double lastPitchAngle = Double.NaN;

  // Robot to turret offset (adjust for your robot)
  private final Translation2d robotToTurret = new Translation2d(0, 0);

  private ShotCalculator() {
    load();
  }

  /** Loads the shot map from the deploy directory. */
  private void load() {
    Path path = Filesystem.getDeployDirectory().toPath().resolve("hub_lookup.json");

    try (BufferedReader reader = Files.newBufferedReader(path)) {
      Gson gson = new Gson();
      JsonObject root = gson.fromJson(reader, JsonObject.class);

      // Load config
      JsonObject config = root.getAsJsonObject("config");
      shooterHeight = config.get("shooter_height_m").getAsDouble();
      targetHeight = config.get("target_height_m").getAsDouble();

      // Load entries array
      JsonArray entriesJson = root.getAsJsonArray("entries");
      int count = 0;

      for (int i = 0; i < entriesJson.size(); i++) {
        JsonObject entry = entriesJson.get(i).getAsJsonObject();
        double distance = entry.get("distance").getAsDouble();
        double pitch = entry.get("pitch").getAsDouble();
        double velocity = entry.get("velocity").getAsDouble();
        double flightTime = entry.get("flight_time").getAsDouble();

        pitchAngleMap.put(distance, pitch);
        exitVelocityMap.put(distance, velocity);
        flightTimeMap.put(distance, flightTime);

        minDistance = Math.min(minDistance, distance);
        maxDistance = Math.max(maxDistance, distance);
        count++;
      }

      loaded = true;
      System.out.println(
          "ShotCalculator: Loaded hub_lookup.json with "
              + count
              + " entries ("
              + minDistance
              + "m - "
              + maxDistance
              + "m)");

    } catch (IOException e) {
      System.err.println("ShotCalculator: Failed to load hub_lookup.json: " + e.getMessage());
    }
  }

  /**
   * Calculates shot parameters for the current robot state using time-of-flight recursion for
   * accurate moving-while-shooting compensation.
   *
   * @return Shot parameters including turret angle, pitch angle, and exit velocity
   */
  public ShootingParameters getParameters() {
    // Get robot state
    Pose2d robotPose = RobotState.getInstance().getRobotPose();
    ChassisSpeeds robotVelocity = RobotState.getInstance().getRobotVelocity();

    // Get alliance-aware target position from FieldConstants
    Translation2d targetPosition = FieldConstants.Hub.topCenterPoint.get().toTranslation2d();

    // Calculate turret position in field coordinates
    Translation2d turretPosition =
        robotPose.getTranslation().plus(robotToTurret.rotateBy(robotPose.getRotation()));

    // Field-relative turret velocity (robot velocity + tangential from rotation)
    double turretVelocityX =
        robotVelocity.vxMetersPerSecond
            - robotVelocity.omegaRadiansPerSecond
                * robotToTurret.rotateBy(robotPose.getRotation()).getY();
    double turretVelocityY =
        robotVelocity.vyMetersPerSecond
            + robotVelocity.omegaRadiansPerSecond
                * robotToTurret.rotateBy(robotPose.getRotation()).getX();

    // Time-of-flight recursion: iterate until distance converges
    double distance = targetPosition.getDistance(turretPosition);
    Translation2d compensatedPosition = turretPosition;
    int iterations = 0;

    for (int i = 0; i < MAX_TOF_ITERATIONS; i++) {
      double clampedDistance = Math.max(minDistance, Math.min(maxDistance, distance));
      double tof = flightTimeMap.get(clampedDistance);

      Translation2d offset = new Translation2d(turretVelocityX * tof, turretVelocityY * tof);
      compensatedPosition = turretPosition.plus(offset);

      double newDistance = targetPosition.getDistance(compensatedPosition);
      iterations = i + 1;

      if (Math.abs(newDistance - distance) < TOF_CONVERGENCE_THRESHOLD) {
        break;
      }
      distance = newDistance;
    }

    // Clamp final distance for lookup
    double lookaheadDistance = Math.max(minDistance, Math.min(maxDistance, distance));

    // Calculate turret angle to compensated target position
    Rotation2d turretAngle = targetPosition.minus(compensatedPosition).getAngle();

    // Normalize angle to [0, 2π) to avoid wrapping issues
    double angleRad = turretAngle.getRadians();
    while (angleRad < 0) angleRad += 2 * Math.PI;
    while (angleRad >= 2 * Math.PI) angleRad -= 2 * Math.PI;
    turretAngle = new Rotation2d(angleRad);

    // Get parameters for compensated distance
    double pitchAngle = pitchAngleMap.get(lookaheadDistance);
    double exitVelocity = exitVelocityMap.get(lookaheadDistance);

    // Calculate velocities using filters
    if (lastTurretAngle == null) lastTurretAngle = turretAngle;
    if (Double.isNaN(lastPitchAngle)) lastPitchAngle = pitchAngle;

    double turretVelocity =
        turretAngleFilter.calculate(
            turretAngle.minus(lastTurretAngle).getRadians() / LOOP_PERIOD_SECS);
    double pitchVelocity =
        pitchAngleFilter.calculate((pitchAngle - lastPitchAngle) / LOOP_PERIOD_SECS);

    lastTurretAngle = turretAngle;
    lastPitchAngle = pitchAngle;

    // Log calculated values
    Logger.recordOutput(
        "ShotCalculator/CompensatedPosition", new Pose2d(compensatedPosition, turretAngle));
    Logger.recordOutput("ShotCalculator/TurretToTargetDistance", lookaheadDistance);
    Logger.recordOutput("ShotCalculator/ToFIterations", iterations);
    Logger.recordOutput("ShotCalculator/PitchAngleDeg", Math.toDegrees(pitchAngle));
    Logger.recordOutput("ShotCalculator/ExitVelocity", exitVelocity);

    return new ShootingParameters(
        turretAngle, turretVelocity, pitchAngle, pitchVelocity, exitVelocity);
  }
}
