package frc.robot.util;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import edu.wpi.first.math.filter.LinearFilter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Filesystem;
import frc.robot.RobotState;
import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import lombok.Getter;
import org.littletonrobotics.junction.Logger;

/**
 * Calculates shooting parameters using interpolating lookup tables generated by
 * scripts/generate_lookup_table.py.
 */
public class ShotCalculator {
  private static final double LOOP_PERIOD_SECS = 0.02; // 20ms
  private static final double EPSILON = 1e-9;

  private static final LoggedTunableNumber newtonMaxIterations =
      new LoggedTunableNumber("ShotCalculator/NewtonMaxIterations", 8.0);
  private static final LoggedTunableNumber newtonResidualToleranceMeters =
      new LoggedTunableNumber("ShotCalculator/NewtonResidualToleranceMeters", 0.001);
  private static final LoggedTunableNumber newtonDistanceToleranceMeters =
      new LoggedTunableNumber("ShotCalculator/NewtonDistanceToleranceMeters", 0.001);
  private static final LoggedTunableNumber newtonDerivativeStepMeters =
      new LoggedTunableNumber("ShotCalculator/NewtonDerivativeStepMeters", 0.05);
  private static final LoggedTunableNumber newtonMinDerivative =
      new LoggedTunableNumber("ShotCalculator/NewtonMinDerivative", 0.05);
  private static final LoggedTunableNumber newtonMaxStepMeters =
      new LoggedTunableNumber("ShotCalculator/NewtonMaxStepMeters", 1.0);

  private static final LoggedTunableNumber stabilityGateEnabled =
      new LoggedTunableNumber("ShotCalculator/StabilityGateEnabled", 1.0);
  private static final LoggedTunableNumber stabilityMaxRobotToShotRatio =
      new LoggedTunableNumber("ShotCalculator/StabilityMaxRobotToShotRatio", 0.65);
  private static final LoggedTunableNumber stabilityMaxLeadAngleDeg =
      new LoggedTunableNumber("ShotCalculator/StabilityMaxLeadAngleDeg", 75.0);
  private static final LoggedTunableNumber stabilityMaxCompensationDistanceMeters =
      new LoggedTunableNumber("ShotCalculator/StabilityMaxCompensationDistanceMeters", 2.0);
  private static final LoggedTunableNumber stabilityMinCommandedHorizontalSpeedMps =
      new LoggedTunableNumber("ShotCalculator/StabilityMinCommandedHorizontalSpeedMps", 1.0);
  private static final LoggedTunableNumber stabilityMaxCommandedSpeedMps =
      new LoggedTunableNumber("ShotCalculator/StabilityMaxCommandedSpeedMps", 18.0);
  private static final LoggedTunableNumber stabilityMaxPitchDeg =
      new LoggedTunableNumber("ShotCalculator/StabilityMaxPitchDeg", 85.0);

  private static ShotCalculator instance;

  public static ShotCalculator getInstance() {
    if (instance == null) instance = new ShotCalculator();
    return instance;
  }

  /** Shooting parameters for a given shot. */
  public record ShootingParameters(
      Rotation2d turretAngle,
      double turretVelocity,
      double pitchAngle,
      double pitchVelocity,
      double exitVelocity) {}

  private record NewtonDistanceSolution(
      double distanceMeters, int iterations, boolean converged, double residualMeters) {}

  private record CompensationSolution(
      Translation2d compensatedPosition,
      double lookaheadDistance,
      int iterations,
      boolean converged,
      boolean usedNewton,
      double residualMeters) {}

  // Lookup tables keyed by distance (meters)
  private final InterpolatingDoubleTreeMap flightTimeMap = new InterpolatingDoubleTreeMap();
  private final InterpolatingDoubleTreeMap velocityVectorXMap = new InterpolatingDoubleTreeMap();
  private final InterpolatingDoubleTreeMap velocityVectorYMap = new InterpolatingDoubleTreeMap();
  private final InterpolatingDoubleTreeMap velocityVectorZMap = new InterpolatingDoubleTreeMap();

  @Getter private double shooterHeight = 0.5;
  @Getter private double targetHeight = 1.75;
  @Getter private double minDistance = Double.MAX_VALUE;
  @Getter private double maxDistance = 0;
  @Getter private boolean loaded = false;
  @Getter private boolean shootOnMoveEnabled = true;

  @Getter private boolean shotStable = false;
  @Getter private boolean lastCompensationConverged = false;
  @Getter private boolean lastCompensationUsedNewton = false;

  // Filters for velocity calculation
  private final LinearFilter turretAngleFilter =
      LinearFilter.movingAverage((int) (0.1 / LOOP_PERIOD_SECS));
  private final LinearFilter pitchAngleFilter =
      LinearFilter.movingAverage((int) (0.1 / LOOP_PERIOD_SECS));

  // State for velocity calculation
  private Rotation2d lastTurretAngle = null;
  private double lastPitchAngle = Double.NaN;

  // Robot to turret offset (adjust for your robot)
  private final Translation2d robotToTurret = new Translation2d(0, 0);

  private ShotCalculator() {
    load();
  }

  /** Enables or disables shoot-on-the-move velocity compensation. */
  public void setShootOnMoveEnabled(boolean enabled) {
    this.shootOnMoveEnabled = enabled;
  }

  /** Loads shot lookups from the deploy directory. */
  private void load() {
    Path deployPath = Filesystem.getDeployDirectory().toPath();
    loadVectorLookup(deployPath.resolve("hub_lookup_vector.json"));
  }

  private void loadVectorLookup(Path path) {
    try (BufferedReader reader = Files.newBufferedReader(path)) {
      Gson gson = new Gson();
      JsonObject root = gson.fromJson(reader, JsonObject.class);
      JsonObject config = root.getAsJsonObject("config");
      shooterHeight = config.get("shooter_height_m").getAsDouble();
      targetHeight = config.get("target_height_m").getAsDouble();

      JsonArray entriesJson = root.getAsJsonArray("entries");
      int count = 0;

      for (int i = 0; i < entriesJson.size(); i++) {
        JsonObject entry = entriesJson.get(i).getAsJsonObject();
        double distance = entry.get("distance").getAsDouble();
        JsonObject vector = entry.getAsJsonObject("velocity_vector_mps");
        double flightTime = entry.get("flight_time").getAsDouble();

        velocityVectorXMap.put(distance, vector.get("x").getAsDouble());
        velocityVectorYMap.put(distance, vector.get("y").getAsDouble());
        velocityVectorZMap.put(distance, vector.get("z").getAsDouble());
        flightTimeMap.put(distance, flightTime);
        minDistance = Math.min(minDistance, distance);
        maxDistance = Math.max(maxDistance, distance);
        count++;
      }

      loaded = count > 0;
      if (loaded) {
        System.out.println(
            "ShotCalculator: Loaded hub_lookup_vector.json with "
                + count
                + " entries ("
                + minDistance
                + "m - "
                + maxDistance
                + "m)");
      }
    } catch (IOException e) {
      loaded = false;
      System.err.println(
          "ShotCalculator: Failed to load hub_lookup_vector.json: " + e.getMessage());
    }
  }

  /**
   * Calculates shot parameters for the current robot state using time-of-flight compensation.
   *
   * @return Shot parameters including turret angle, pitch angle, and exit velocity
   */
  public ShootingParameters getParameters() {
    if (!loaded) {
      shotStable = false;
      lastCompensationConverged = false;
      lastCompensationUsedNewton = false;
      return new ShootingParameters(Rotation2d.kZero, 0.0, 0.0, 0.0, 0.0);
    }

    Pose2d robotPose = RobotState.getInstance().getRobotPose();
    ChassisSpeeds robotVelocity = RobotState.getInstance().getRobotVelocity();

    Translation2d targetPosition = getAllianceTransposedTargetPosition();
    Translation2d turretPosition =
        robotPose.getTranslation().plus(robotToTurret.rotateBy(robotPose.getRotation()));

    // Vector-only shoot-on-move: do not apply distance/time lookahead.
    // We keep target distance based on current geometry and compensate purely by velocity
    // subtraction.
    double currentDistance = targetPosition.getDistance(turretPosition);
    CompensationSolution compensationSolution =
        new CompensationSolution(
            turretPosition, clampDistance(currentDistance), 0, true, false, 0.0);

    lastCompensationConverged = compensationSolution.converged();
    lastCompensationUsedNewton = compensationSolution.usedNewton();

    Rotation2d lookupYaw =
        normalizeTo0To2Pi(
            targetPosition.minus(compensationSolution.compensatedPosition()).getAngle());
    Translation3d lookupVector = getLookupVector(compensationSolution.lookaheadDistance());
    Translation3d requiredFieldVelocity =
        ShotVectorCompensator.orientLookupVectorToField(lookupVector, lookupYaw);

    ShotVectorCompensator.CompensatedShot shot =
        shootOnMoveEnabled
            ? ShotVectorCompensator.compensateForRobotMotion(
                requiredFieldVelocity, robotVelocity, robotPose.getRotation(), robotToTurret)
            : ShotVectorCompensator.fromShooterRelativeVector(requiredFieldVelocity);

    Rotation2d turretAngle = normalizeTo0To2Pi(shot.yaw());
    double pitchAngle = shot.pitch();
    double exitVelocity = shot.exitVelocity();

    if (lastTurretAngle == null) lastTurretAngle = turretAngle;
    if (Double.isNaN(lastPitchAngle)) lastPitchAngle = pitchAngle;

    double turretVelocity =
        turretAngleFilter.calculate(
            turretAngle.minus(lastTurretAngle).getRadians() / LOOP_PERIOD_SECS);
    double pitchVelocity =
        pitchAngleFilter.calculate((pitchAngle - lastPitchAngle) / LOOP_PERIOD_SECS);

    lastTurretAngle = turretAngle;
    lastPitchAngle = pitchAngle;

    shotStable =
        evaluateStabilityGate(
            lookupYaw,
            shot,
            turretPosition,
            compensationSolution.compensatedPosition(),
            compensationSolution);

    Logger.recordOutput("ShotCalculator/ShootOnMoveEnabled", shootOnMoveEnabled);
    Logger.recordOutput("ShotCalculator/VectorLookupLoaded", loaded);
    Logger.recordOutput("ShotCalculator/ShotStable", shotStable);
    Logger.recordOutput("ShotCalculator/CompensationConverged", lastCompensationConverged);
    Logger.recordOutput("ShotCalculator/CompensationUsedNewton", lastCompensationUsedNewton);
    Logger.recordOutput("ShotCalculator/CompensationIterations", compensationSolution.iterations());
    Logger.recordOutput(
        "ShotCalculator/CompensationResidualMeters", compensationSolution.residualMeters());
    Logger.recordOutput(
        "ShotCalculator/CompensatedPosition",
        new Pose2d(compensationSolution.compensatedPosition(), turretAngle));
    Logger.recordOutput(
        "ShotCalculator/TurretToTargetDistance", compensationSolution.lookaheadDistance());
    Logger.recordOutput("ShotCalculator/PitchAngleDeg", Math.toDegrees(pitchAngle));
    Logger.recordOutput("ShotCalculator/ExitVelocity", exitVelocity);
    Logger.recordOutput(
        "ShotCalculator/RequiredFieldVelocity",
        new double[] {
          shot.requiredFieldVelocity().getX(),
          shot.requiredFieldVelocity().getY(),
          shot.requiredFieldVelocity().getZ()
        });
    Logger.recordOutput(
        "ShotCalculator/ShooterFieldVelocity",
        new double[] {
          shot.shooterFieldVelocity().getX(),
          shot.shooterFieldVelocity().getY(),
          shot.shooterFieldVelocity().getZ()
        });
    Logger.recordOutput(
        "ShotCalculator/CommandedShooterVelocity",
        new double[] {
          shot.shooterRelativeVelocity().getX(),
          shot.shooterRelativeVelocity().getY(),
          shot.shooterRelativeVelocity().getZ()
        });

    return new ShootingParameters(
        turretAngle, turretVelocity, pitchAngle, pitchVelocity, exitVelocity);
  }

  private CompensationSolution solveCompensation(
      Translation2d turretPosition,
      Translation2d targetPosition,
      Translation3d turretFieldVelocity,
      double initialDistance) {
    if (!shootOnMoveEnabled) {
      return new CompensationSolution(
          turretPosition, clampDistance(initialDistance), 0, true, false, 0.0);
    }

    NewtonDistanceSolution newtonSolution =
        solveDistanceNewton(turretPosition, targetPosition, turretFieldVelocity, initialDistance);
    double lookaheadDistance = newtonSolution.distanceMeters();
    double tof = flightTimeMap.get(lookaheadDistance);
    Translation2d compensatedPosition =
        turretPosition.plus(
            new Translation2d(turretFieldVelocity.getX() * tof, turretFieldVelocity.getY() * tof));

    return new CompensationSolution(
        compensatedPosition,
        lookaheadDistance,
        newtonSolution.iterations(),
        newtonSolution.converged(),
        true,
        newtonSolution.residualMeters());
  }

  private NewtonDistanceSolution solveDistanceNewton(
      Translation2d turretPosition,
      Translation2d targetPosition,
      Translation3d turretFieldVelocity,
      double initialDistance) {
    int maxIterations = Math.max(1, (int) Math.round(newtonMaxIterations.get()));
    double residualTolerance = Math.max(1e-6, newtonResidualToleranceMeters.get());
    double distanceTolerance = Math.max(1e-6, newtonDistanceToleranceMeters.get());
    double minDerivative = Math.max(1e-4, newtonMinDerivative.get());
    double maxStepMeters = Math.max(0.01, newtonMaxStepMeters.get());

    double distance = clampDistance(initialDistance);
    int iterations = 0;
    boolean converged = false;
    double residualMeters =
        Math.abs(
            computeDistanceResidual(distance, turretPosition, targetPosition, turretFieldVelocity));

    for (int i = 0; i < maxIterations; i++) {
      iterations = i + 1;

      double tof = flightTimeMap.get(distance);
      Translation2d predicted =
          turretPosition.plus(
              new Translation2d(
                  turretFieldVelocity.getX() * tof, turretFieldVelocity.getY() * tof));
      Translation2d delta = targetPosition.minus(predicted);
      double range = delta.getNorm();

      double f = distance - range;
      residualMeters = Math.abs(f);
      if (residualMeters <= residualTolerance) {
        converged = true;
        break;
      }

      double dtdd = flightTimeDerivative(distance);
      double dot =
          delta.getX() * turretFieldVelocity.getX() + delta.getY() * turretFieldVelocity.getY();
      double derivative = 1.0 + (dot / Math.max(range, EPSILON)) * dtdd;

      if (!Double.isFinite(derivative) || Math.abs(derivative) < minDerivative) {
        break;
      }

      double step = f / derivative;
      step = Math.max(-maxStepMeters, Math.min(maxStepMeters, step));

      double nextDistance = clampDistance(distance - step);
      if (!Double.isFinite(nextDistance)) {
        break;
      }
      if (Math.abs(nextDistance - distance) <= distanceTolerance) {
        distance = nextDistance;
        residualMeters =
            Math.abs(
                computeDistanceResidual(
                    distance, turretPosition, targetPosition, turretFieldVelocity));
        converged = residualMeters <= residualTolerance;
        break;
      }

      distance = nextDistance;
    }

    return new NewtonDistanceSolution(distance, iterations, converged, residualMeters);
  }

  private boolean evaluateStabilityGate(
      Rotation2d lookupYaw,
      ShotVectorCompensator.CompensatedShot shot,
      Translation2d turretPosition,
      Translation2d compensatedPosition,
      CompensationSolution compensationSolution) {
    if (!shootOnMoveEnabled || stabilityGateEnabled.get() < 0.5) {
      return true;
    }

    double requiredHorizontalSpeed =
        Math.hypot(shot.requiredFieldVelocity().getX(), shot.requiredFieldVelocity().getY());
    double shooterFieldHorizontalSpeed =
        Math.hypot(shot.shooterFieldVelocity().getX(), shot.shooterFieldVelocity().getY());
    double commandedHorizontalSpeed =
        Math.hypot(shot.shooterRelativeVelocity().getX(), shot.shooterRelativeVelocity().getY());
    double robotToShotRatio =
        shooterFieldHorizontalSpeed / Math.max(requiredHorizontalSpeed, EPSILON);
    double leadAngleDeg =
        Math.toDegrees(Math.abs(normalizeToMinusPiToPi(shot.yaw().minus(lookupYaw).getRadians())));
    double compensationDistance = turretPosition.getDistance(compensatedPosition);
    double maxPitchRad = Math.toRadians(stabilityMaxPitchDeg.get());

    boolean stable =
        compensationSolution.converged()
            && Double.isFinite(shot.exitVelocity())
            && Double.isFinite(shot.pitch())
            && robotToShotRatio <= stabilityMaxRobotToShotRatio.get()
            && leadAngleDeg <= stabilityMaxLeadAngleDeg.get()
            && compensationDistance <= stabilityMaxCompensationDistanceMeters.get()
            && commandedHorizontalSpeed >= stabilityMinCommandedHorizontalSpeedMps.get()
            && shot.exitVelocity() <= stabilityMaxCommandedSpeedMps.get()
            && Math.abs(shot.pitch()) <= maxPitchRad;

    Logger.recordOutput("ShotCalculator/Stability/RobotToShotRatio", robotToShotRatio);
    Logger.recordOutput("ShotCalculator/Stability/LeadAngleDeg", leadAngleDeg);
    Logger.recordOutput("ShotCalculator/Stability/CompensationDistanceM", compensationDistance);
    Logger.recordOutput(
        "ShotCalculator/Stability/CommandedHorizontalSpeedMps", commandedHorizontalSpeed);
    Logger.recordOutput("ShotCalculator/Stability/CommandedPitchDeg", Math.toDegrees(shot.pitch()));

    return stable;
  }

  private double flightTimeDerivative(double distance) {
    double derivativeStep = Math.max(0.001, newtonDerivativeStepMeters.get());
    double low = clampDistance(distance - derivativeStep);
    double high = clampDistance(distance + derivativeStep);
    double span = high - low;
    if (span < EPSILON) return 0.0;
    return (flightTimeMap.get(high) - flightTimeMap.get(low)) / span;
  }

  private double computeDistanceResidual(
      double distance,
      Translation2d turretPosition,
      Translation2d targetPosition,
      Translation3d turretFieldVelocity) {
    double clampedDistance = clampDistance(distance);
    double tof = flightTimeMap.get(clampedDistance);
    Translation2d predicted =
        turretPosition.plus(
            new Translation2d(turretFieldVelocity.getX() * tof, turretFieldVelocity.getY() * tof));
    return clampedDistance - targetPosition.getDistance(predicted);
  }

  private double clampDistance(double distance) {
    return Math.max(minDistance, Math.min(maxDistance, distance));
  }

  private Translation3d getLookupVector(double distance) {
    return new Translation3d(
        velocityVectorXMap.get(distance),
        velocityVectorYMap.get(distance),
        velocityVectorZMap.get(distance));
  }

  /** Returns target position transposed for the current alliance (blue or red). */
  private Translation2d getAllianceTransposedTargetPosition() {
    if (DriverStation.getAlliance().isPresent()
        && DriverStation.getAlliance().get() == DriverStation.Alliance.Red) {
      Logger.recordOutput("ShotCalculator/Alliance", "Red");
      return FieldConstants.Hub.topCenterPoint.getRed().toTranslation2d();
    }

    Logger.recordOutput("ShotCalculator/Alliance", "Blue");
    return FieldConstants.Hub.topCenterPoint.getBlue().toTranslation2d();
  }

  private static Rotation2d normalizeTo0To2Pi(Rotation2d angle) {
    double angleRad = angle.getRadians();
    while (angleRad < 0) angleRad += 2 * Math.PI;
    while (angleRad >= 2 * Math.PI) angleRad -= 2 * Math.PI;
    return Rotation2d.fromRadians(angleRad);
  }

  private static double normalizeToMinusPiToPi(double angleRad) {
    return Math.atan2(Math.sin(angleRad), Math.cos(angleRad));
  }
}
